version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: infnet2022
      MYSQL_DATABASE: ventura
    ports:
     - "3306:3306"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "8080:8081"